#!/bin/bash
: -+- utf8 -+- shellscript :'
:  (c) 2018 MIT License
:  Marcel Bobolz
:  <ergotamin.source@gmail.com>
: ------------------------ :'

function dumpzero() {
	typeset devname="${1}"
	typeset blocks=$(($(LC_ALL=C fdisk -l --bytes ${devname} | head -1 | cut -d ' ' -f 5) / $((1024 * 1024))))
	printf "\t$(tput smul)Device: ${devname}$(tput sgr0)\n" \
		"\t$(tput setaf 33)Disksize(blocks to write)$(tput sgr0):\n" \
		"\t$(tput setaf 2)${blocks}$(tput sgr0) [MegaBytes]\n" \
		"\t$(tput setaf 1)! WARNING: DATA-WIPING NOW !\n$(tput sgr0)"
	dd if=/dev/zero of=${devname} bs=1M count=${blocks} seek=0 2>/dev/zero
	return ${?}
}

if [ ${#} -eq 0 ]; then
	exit 1
elif [ ! -b ${1} ]; then
	exit 1
else
	dumpzero ${1}
	exit $?
fi
