#!/bin/bash
: -+- utf8 -+- shellscript -+- '
: -----------------------------
:  (c) 2018 MIT License
:  Marcel Bobolz
:  <ergotamin.source@gmail.com>
: -----------------------------'

function json::show() {
	local JSONPATH="$1"
	local JSONFILE="$2"
	cat - <<-NODE | node -
		const json = require("$JSONFILE");
		const want = json$JSONPATH;
		
		if (typeof want === 'object'){
		      Object.keys(want).forEach(entry => {
		        console.log(entry.toString() + ": " + want[entry].toString());
		      });
		} else if (want != null) {
		      console.log(want.toString());
		} else {
		  console.log("No such entry... !");
		}
	NODE
	return $?
}

if [[ $# -eq 2 ]] && [[ -e $2 ]]; then
	json::show $1 $2
else
	echo '
  Usage:
    json-show [KEY] [JSONFILE]
    Look for the value(s) of KEY in JSONFILE.
  '
fi
exit $?
